"""Companion appendix table: Haiku-4.5 MT-Bench under strict vs permissive parser.

The body's strict (FastChat-faithful) parser only matches `[[N]]`. Haiku-4.5
emits `[[rating: N]]` ~12-74% of the time depending on prompt condition,
which the strict parser rejects as a parse failure. This is a real condition
effect on FORMAT ADHERENCE (the controls table reports it as a parse-rate
subscript).

This companion table answers a separate question: among items where Haiku
emits *some* parseable rating in either format, do the underlying scores
differ across conditions? In other words, is the condition shifting only
format adherence, or also the rating distribution?

Inputs:
  results/controls_2026-05-09/mtbench/n*_*claude-haiku-45*.json.gz
  (re-parses raw_response with both strict and permissive regex)

Output:
  writing/base_article/shared/tables_controls/tab_controls_haiku_parser.tex
"""

from __future__ import annotations

import argparse
import gzip
import json
import re
from pathlib import Path

POC_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = POC_ROOT / "results" / "controls_2026-05-09" / "mtbench"
DEFAULT_OUTPUT = (
    POC_ROOT / "writing" / "base_article" / "tables_controls"
    / "tab_controls_haiku_parser.tex"
)

CONDITIONS = ["baseline", "multi_msg", "system_distrust", "tool_wrapped_v2", "tool_distrust_v2"]
COND_DISPLAY = {
    "baseline": r"\texttt{UserOnly}",
    "multi_msg": r"\texttt{UserSys}",
    "system_distrust": r"\texttt{SystemDistrust}",
    "tool_wrapped_v2": r"\texttt{ToolWrapped}",
    "tool_distrust_v2": r"\texttt{ToolDistrust}",
}

# Strict (FastChat-faithful) — what the body's main pipeline uses.
STRICT_PRIMARY = re.compile(r"\[\[(\d+\.?\d*)\]\]")
STRICT_FALLBACK = re.compile(r"\[(\d+\.?\d*)\]")

# Permissive: also accept "[[rating: N]]" / "[[score: N]]" / "[[grade: N]]".
PERMISSIVE = re.compile(
    r"\[\[\s*(?:rating|score|grade)?[:\s]*(\d+\.?\d*)\s*\]\]", re.I
)


def parse_strict(text: str) -> int | None:
    if not text:
        return None
    m = STRICT_PRIMARY.search(text) or STRICT_FALLBACK.search(text)
    if m:
        try:
            return int(float(m.group(1)))
        except (TypeError, ValueError):
            return None
    return None


def parse_permissive(text: str) -> int | None:
    if not text:
        return None
    m = PERMISSIVE.search(text)
    if m:
        try:
            return int(float(m.group(1)))
        except (TypeError, ValueError):
            return None
    return parse_strict(text)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT)
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return p.parse_args()


def main() -> int:
    args = parse_args()

    matrix_summary_path = args.input_dir / "matrix_summary.json.gz"
    if matrix_summary_path.exists():
        with gzip.open(matrix_summary_path, "rt") as f:
            ms = json.load(f)
        referenced = {Path(e["raw_output"]).name for e in ms.get("models", []) if e.get("raw_output")}
        haiku_files = sorted(
            p for p in args.input_dir.glob("*claude-haiku-45*.json.gz")
            if p.name in referenced
        )
    else:
        haiku_files = sorted(args.input_dir.glob("*claude-haiku-45*.json.gz"))
        haiku_files = [p for p in haiku_files if not p.name.endswith("_summary.json.gz")]
    if not haiku_files:
        print(f"No Haiku raw files in {args.input_dir}")
        return 1

    rows: list[dict] = []
    for path in haiku_files:
        with gzip.open(path, "rt") as f:
            rows.extend(json.load(f))

    # Aggregate per condition: strict and permissive
    per_cond: dict[str, dict] = {}
    for cond in CONDITIONS:
        cond_rows = [
            r for r in rows
            if r["condition"] == cond and r.get("is_under_attack") is False
        ]
        n = len(cond_rows)
        strict_scores: list[int] = []
        perm_scores: list[int] = []
        for r in cond_rows:
            raw = r.get("raw") or ""
            s = parse_strict(raw)
            if s is not None:
                strict_scores.append(s)
            p = parse_permissive(raw)
            if p is not None:
                perm_scores.append(p)
        per_cond[cond] = {
            "n": n,
            "strict_n": len(strict_scores),
            "perm_n": len(perm_scores),
            "strict_mean": sum(strict_scores) / len(strict_scores) if strict_scores else float("nan"),
            "perm_mean": sum(perm_scores) / len(perm_scores) if perm_scores else float("nan"),
        }

    # Render LaTeX
    lines: list[str] = []
    lines.append("% Auto-generated by scripts/gen_haiku_parser_compare.py. DO NOT EDIT.\n")
    lines.append(r"\begin{table*}[!tbp]" + "\n")
    lines.append(r"\centering" + "\n")
    lines.append(
        r"\caption{\textbf{Parser sensitivity, Haiku-4.5 on MT-Bench non-adversarial controls.} "
        r"Haiku-4.5 frequently emits \texttt{[[rating: N]]} instead of the "
        r"\texttt{[[N]]} format the FastChat parser expects. The strict parse "
        r"rate varies sharply by condition (32\% to 72\%), but a permissive "
        r"parser that also accepts \texttt{[[rating: N]]} recovers nearly all "
        r"items, so this format mismatch accounts for essentially all of the "
        r"parse failures.}"
        + "\n"
    )
    lines.append(r"\label{tab:controls_haiku_parser}" + "\n")
    lines.append(r"\begingroup\addfontfeatures{Numbers=Monospaced}%" + "\n")
    lines.append(r"\begin{tabular}{lrrrr}" + "\n")
    lines.append(r"\toprule" + "\n")
    lines.append(
        r"Condition & strict parse rate & strict mean & "
        r"permissive parse rate & permissive mean \\" + "\n"
    )
    lines.append(r"\midrule" + "\n")
    for cond in CONDITIONS:
        d = per_cond[cond]
        n = d["n"]
        s_rate = (d["strict_n"] / n * 100) if n else 0
        p_rate = (d["perm_n"] / n * 100) if n else 0
        lines.append(
            f"{COND_DISPLAY[cond]} & {s_rate:.0f}\\% & {d['strict_mean']:.2f} & "
            f"{p_rate:.0f}\\% & {d['perm_mean']:.2f} \\\\\n"
        )
    lines.append(r"\bottomrule" + "\n")
    lines.append(r"\end{tabular}\endgroup" + "\n")
    lines.append(r"\end{table*}" + "\n")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("".join(lines))
    print(f"wrote {args.output}")

    # Also dump a JSON summary for cross-checks
    summary_path = args.output.parent / "_haiku_parser_summary.json"
    summary_path.write_text(json.dumps(per_cond, indent=2))
    print(f"wrote {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
